name: TheBridge
version: 1.0.0
main: nl.kmc.bridge.TheBridgePlugin
api-version: '1.21'
authors: [KMC]
depend: [KMCCore]
description: The Bridge minigame for KMC tournaments

commands:
  bridge:
    description: The Bridge control + setup
    aliases: [tb]
    usage: /bridge <start|stop|setworld|createteam|...>
    permission: bridge.admin

permissions:
  bridge.admin:
    description: Bridge admin commands
    default: op
