name: Send Discord Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"📦 **Nieuwe push naar repository!**\n👤 Auteur: $COMMIT_AUTHOR\n📝 Message: $COMMIT_MESSAGE\n🔗 $COMMIT_URL\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
